### ISSUE TITLE
"show" commands fail to run as admin user (dmidecode error)

### ISSUE THREAD

**Issue by deke997** [sonic-net/SONiC#1494]
When running the following command: `admin@sonic:~$ show interfaces status`

I get this error:

```
admin@sonic:~$ show interfaces status
failed to import plugin show.plugins.cisco-8000: [Errno 2] No such file or directory: 'dmidecode'
Traceback (most recent call last):
  File "/usr/local/bin/intfutil", line 836, in <module>
    main()
  File "/usr/local/bin/intfutil", line 819, in main
    interface_stat.display_intf_status()
  File "/usr/local/bin/intfutil", line 448, in display_intf_status
    self.get_intf_status()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/multi_asic.py", line 157, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/intfutil", line 535, in get_intf_status
    self.table += self.generate_intf_status()
  File "/usr/local/bin/intfutil", line 479, in generate_intf_status
    port_oper_speed_get(self.db, key),
  File "/usr/local/bin/intfutil", line 202, in port_oper_speed_get
    return appl_db_port_status_get(db, intf_name, PORT_SPEED)
  File "/usr/local/bin/intfutil", line 167, in appl_db_port_status_get
    optics_type = port_optics_get(appl_db, intf_name, PORT_OPTICS_TYPE)
  File "/usr/local/bin/intfutil", line 224, in port_optics_get
    if is_rj45_port(intf_name):
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/platform_sfputil_helper.py", line 119, in is_rj45_port
    import sonic_platform
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/__init__.py", line 7, in <module>
    from sonic_platform import *
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/platform.py", line 12, in <module>
    from sonic_platform.chassis import Chassis
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py", line 18, in <module>
    from sonic_platform.component import Component
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/component.py", line 28, in <module>
    class Component(ComponentBase):
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/component.py", line 34, in Component
    get_bios_version()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/component.py", line 19, in get_bios_version
    return subprocess.check_output(['dmidecode', '-s', 'system-version']).strip().decode()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dmidecode'
```

This is clearly caused by the inability of the "admin" user to run dmidecode. If I run the same command as root or with sudo, it functions properly:

```
admin@sonic:~$ sudo show interfaces status
  Interface        Lanes    Speed    MTU    FEC            Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  -----------  -------  -----  -----  ---------------  ------  ------  -------  ------  ----------
  Ethernet0            1       1G   9100    N/A       oneGigE1/1  routed    down       up     N/A         N/A
  Ethernet1            2       1G   9100    N/A       oneGigE1/2  routed    down       up     N/A         N/A
  Ethernet2            3       1G   9100    N/A       oneGigE1/3  routed    down       up     N/A         N/A
  Ethernet3            4       1G   9100    N/A       oneGigE1/4  routed    down       up     N/A         N/A
  Ethernet4            5       1G   9100    N/A       oneGigE1/5  routed    down       up     N/A         N/A
  Ethernet5            6       1G   9100    N/A       oneGigE1/6  routed    down       up     N/A         N/A
  Ethernet6            7       1G   9100    N/A       oneGigE1/7  routed    down       up     N/A         N/A
  Ethernet7            8       1G   9100    N/A       oneGigE1/8  routed    down       up     N/A         N/A
  Ethernet8            9       1G   9100    N/A       oneGigE1/9  routed    down       up     N/A         N/A
  Ethernet9           10       1G   9100    N/A      oneGigE1/10  routed    down       up     N/A         N/A
 Ethernet10           11       1G   9100    N/A      oneGigE1/11  routed    down       up     N/A         N/A
 Ethernet11           12       1G   9100    N/A      oneGigE1/12  routed    down       up     N/A         N/A
 Ethernet12           13       1G   9100    N/A      oneGigE1/13  routed    down       up     N/A         N/A
 Ethernet13           14       1G   9100    N/A      oneGigE1/14  routed    down       up     N/A         N/A
 Ethernet14           15       1G   9100    N/A      oneGigE1/15  routed    down       up     N/A         N/A
 Ethernet15           16       1G   9100    N/A      oneGigE1/16  routed    down       up     N/A         N/A
 Ethernet16           17       1G   9100    N/A      oneGigE1/17  routed    down       up     N/A         N/A
 Ethernet17           18       1G   9100    N/A      oneGigE1/18  routed    down       up     N/A         N/A
 Ethernet18           19       1G   9100    N/A      oneGigE1/19  routed    down       up     N/A         N/A
 Ethernet19           20       1G   9100    N/A      oneGigE1/20  routed    down       up     N/A         N/A
 Ethernet20           21       1G   9100    N/A      oneGigE1/21  routed    down       up     N/A         N/A
 Ethernet21           22       1G   9100    N/A      oneGigE1/22  routed    down       up     N/A         N/A
 Ethernet22           23       1G   9100    N/A      oneGigE1/23  routed    down       up     N/A         N/A
 Ethernet23           24       1G   9100    N/A      oneGigE1/24  routed    down       up     N/A         N/A
 Ethernet24           25       1G   9100    N/A      oneGigE1/25  routed    down       up     N/A         N/A
 Ethernet25           26       1G   9100    N/A      oneGigE1/26  routed    down       up     N/A         N/A
 Ethernet26           27       1G   9100    N/A      oneGigE1/27  routed    down       up     N/A         N/A
 Ethernet27           28       1G   9100    N/A      oneGigE1/28  routed    down       up     N/A         N/A
 Ethernet28           29       1G   9100    N/A      oneGigE1/29  routed    down       up     N/A         N/A
 Ethernet29           30       1G   9100    N/A      oneGigE1/30  routed    down       up     N/A         N/A
 Ethernet30           31       1G   9100    N/A      oneGigE1/31  routed    down       up     N/A         N/A
 Ethernet31           32       1G   9100    N/A      oneGigE1/32  routed    down       up     N/A         N/A
 Ethernet32           33       1G   9100    N/A      oneGigE1/33  routed    down       up     N/A         N/A
 Ethernet33           34       1G   9100    N/A      oneGigE1/34  routed    down       up     N/A         N/A
 Ethernet34           35       1G   9100    N/A      oneGigE1/35  routed    down       up     N/A         N/A
 Ethernet35           36       1G   9100    N/A      oneGigE1/36  routed    down       up     N/A         N/A
 Ethernet36           37       1G   9100    N/A      oneGigE1/37  routed    down       up     N/A         N/A
 Ethernet37           38       1G   9100    N/A      oneGigE1/38  routed    down       up     N/A         N/A
 Ethernet38           39       1G   9100    N/A      oneGigE1/39  routed    down       up     N/A         N/A
 Ethernet39           40       1G   9100    N/A      oneGigE1/40  routed    down       up     N/A         N/A
 Ethernet40           41       1G   9100    N/A      oneGigE1/41  routed    down       up     N/A         N/A
 Ethernet41           42       1G   9100    N/A      oneGigE1/42  routed    down       up     N/A         N/A
 Ethernet42           43       1G   9100    N/A      oneGigE1/43  routed    down       up     N/A         N/A
 Ethernet43           44       1G   9100    N/A      oneGigE1/44  routed    down       up     N/A         N/A
 Ethernet44           45       1G   9100    N/A      oneGigE1/45  routed    down       up     N/A         N/A
 Ethernet45           46       1G   9100    N/A      oneGigE1/46  routed    down       up     N/A         N/A
 Ethernet46           47       1G   9100    N/A      oneGigE1/47  routed    down       up     N/A         N/A
 Ethernet47           48       1G   9100    N/A      oneGigE1/48  routed    down       up     N/A         N/A
 Ethernet48           64      10G   9100    N/A      tenGigE1/49  routed    down       up     N/A         N/A
 Ethernet49           63      10G   9100    N/A      tenGigE1/50  routed    down       up     N/A         N/A
 Ethernet50           62      10G   9100    N/A      tenGigE1/51  routed    down       up     N/A         N/A
 Ethernet51           61      10G   9100    N/A      tenGigE1/52  routed    down       up     N/A         N/A
 Ethernet52  69,70,71,72     100G   9100    N/A  hundredGigE1/53  routed    down       up     N/A         N/A
 Ethernet56  73,74,75,76     100G   9100    N/A  hundredGigE1/54  routed    down       up     N/A         N/A
```

Here is my version info. 
```
admin@sonic:~$ sudo show version

SONiC Software Version: SONiC.202305.383152-efe5ca8c4
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: efe5ca8c4
Build date: Tue Oct 10 13:53:29 UTC 2023
Built by: AzDevOps@vmss-soni0026WP

Platform: x86_64-dellemc_n3248te_c3338-r0
HwSKU: DellEMC-N3248TE
ASIC: broadcom
ASIC Count: 1
Serial Number: 
Model Number: 0MTT55
Hardware Revision:
Uptime: 14:56:14 up 19 min,  1 user,  load average: 0.48, 0.92, 0.94
Date: Wed 11 Oct 2023 14:56:14
```

The same behavior occurs on the Master build as well

**Comment by justindthomas** [comment]
Oh, funny - I didn't see this here.

I think the devs only look at issues in the `sonic-buildimage` repo. Here's the issue I opened earlier today that echoes this problem: https://github.com/sonic-net/sonic-buildimage/issues/16878
