### ISSUE TITLE
ModuleNotFoundError: No module named 'sonic_platform'

### ISSUE THREAD

**Issue by lgzcoollg** [sonic-net/SONiC#1779]
**We do not triage issue for this repo. All issues are triaged in sonic-net/sonic-buildimage repo**

root@sonic:~# show version 

SONiC Software Version: SONiC.202405.612889-a2ea2a9dd
SONiC OS Version: 12
Distribution: Debian 12.5
Kernel: 6.1.0-11-2-amd64
Build commit: a2ea2a9dd
Build date: Tue Aug  6 13:40:31 UTC 2024
Built by: azureuser@a31fcf8ec000000

Platform: x86_64-accton_as7716_32x-r0
HwSKU: Accton-AS7716-32X
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 23:00:49 up 39 min,  1 user,  load average: 0.61, 0.40, 0.38
Date: Sat 27 Jan 2024 23:00:49

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-syncd-brcm             202405.612889-a2ea2a9dd   50ba9d21be74   730MB
docker-syncd-brcm             latest                    50ba9d21be74   730MB
docker-gbsyncd-broncos        202405.612889-a2ea2a9dd   10e7ae70118c   366MB
docker-gbsyncd-broncos        latest                    10e7ae70118c   366MB
docker-gbsyncd-credo          202405.612889-a2ea2a9dd   00a0b1e16344   339MB
docker-gbsyncd-credo          latest                    00a0b1e16344   339MB
docker-macsec                 latest                    4d1029955d80   362MB
docker-dhcp-relay             latest                    fa9b93bdbb21   340MB
docker-platform-monitor       202405.612889-a2ea2a9dd   90b705d2bf77   456MB
docker-platform-monitor       latest                    90b705d2bf77   456MB
docker-orchagent              202405.612889-a2ea2a9dd   bb275d2318d5   372MB
docker-orchagent              latest                    bb275d2318d5   372MB
docker-nat                    202405.612889-a2ea2a9dd   5f2d2f96ff14   362MB
docker-nat                    latest                    5f2d2f96ff14   362MB
docker-fpm-frr                202405.612889-a2ea2a9dd   a11fa3320abc   391MB
docker-fpm-frr                latest                    a11fa3320abc   391MB
docker-snmp                   202405.612889-a2ea2a9dd   db5fedfa4ea6   370MB
docker-snmp                   latest                    db5fedfa4ea6   370MB
docker-eventd                 202405.612889-a2ea2a9dd   6a2770ee2f4b   330MB
docker-eventd                 latest                    6a2770ee2f4b   330MB
docker-sflow                  202405.612889-a2ea2a9dd   c1e00e2910ad   360MB
docker-sflow                  latest                    c1e00e2910ad   360MB
docker-teamd                  202405.612889-a2ea2a9dd   c6501b570c4b   359MB
docker-teamd                  latest                    c6501b570c4b   359MB
docker-mux                    202405.612889-a2ea2a9dd   8b81a79fb53f   382MB
docker-mux                    latest                    8b81a79fb53f   382MB
docker-lldp                   202405.612889-a2ea2a9dd   7f149422e6ec   376MB
docker-lldp                   latest                    7f149422e6ec   376MB
docker-sonic-gnmi             202405.612889-a2ea2a9dd   b96c2271938f   415MB
docker-sonic-gnmi             latest                    b96c2271938f   415MB
docker-database               202405.612889-a2ea2a9dd   cfde52dfb6d9   339MB
docker-database               latest                    cfde52dfb6d9   339MB
docker-sonic-mgmt-framework   202405.612889-a2ea2a9dd   81dca62903b6   417MB
docker-sonic-mgmt-framework   latest                    81dca62903b6   417MB
docker-router-advertiser      202405.612889-a2ea2a9dd   c5e899731ca0   331MB
docker-router-advertiser      latest                    c5e899731ca0   331MB

root@sonic:~# show platform syseeprom                                                                          
Traceback (most recent call last):
  **File "/usr/local/bin/decode-syseeprom", line 18, in <module>
    import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'**

root@sonic:~# show platform fan
Fan Not detected

root@sonic:~# sfpshow presence                                                                                 
Port         Presence
-----------  -----------
Ethernet0    Not present
Ethernet4    Not present
**Ethernet8    Not present**
Ethernet12   Not present

root@sonic:~# show interfaces status
  Interface            Lanes    Speed    MTU    FEC          Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----  -------------  ------  ------  -------  ------  ----------
  Ethernet0      49,50,51,52     100G   9100    N/A   hundredGigE1  routed    down       up     N/A         N/A
  Ethernet4      53,54,55,56     100G   9100    N/A   hundredGigE2  routed    down       up     N/A         N/A
  **Ethernet8      57,58,59,60     100G   9100    N/A   hundredGigE3  routed      up       up     N/A         N/A**
 Ethernet12      61,62,63,64     100G   9100    N/A   hundredGigE4  routed    down       up     N/A         N/A

root@sonic:~# sfputil 
Traceback (most recent call last):
  File "/usr/local/bin/sfputil", line 5, in <module>
    from sfputil.main import cli
  File "/usr/local/lib/python3.11/dist-packages/sfputil/main.py", line 18, in <module>
    **import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'**
root@sonic:~#

**Comment by lgzcoollg** [comment]
close
